name: Build Cushion Trainer APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Unzip project
        run: unzip CushionTrainer_Gradle4_Ready.zip -d appsrc

      - name: Build APK
        run: |
          cd appsrc
          ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: CushionTrainer-APK
          path: appsrc/app/build/outputs/apk/debug/app-debug.apk
